export LC_ALL=es_ES.UTF-8
export LANG=es_ES.UTF-8
# Load Antigen
source ~/.config/antigen/antigen.zsh
# Load Antigen configurations
antigen init ~/.config/antigen/antigenrc

if [ "$TMUX" = "" ]; then tmux; fi
