export LC_ALL=es_ES.UTF-8
export LANG=es_ES.UTF-8
export TERM=xterm-256color
export VISUAL="nvim"
export EDITOR="$VISUAL"
export ZSH_TMUX_AUTOSTART=true

# Load Antigen
source ~/.config/antigen/antigen.zsh

# Load Antigen configurations
antigen init ~/.config/antigen/antigenrc

# Alias
alias v=nvim
alias vim=nvim
# alias python=/usr/local/bin/python3
# alias pip=/usr/local/bin/pip3
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
[ -f "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env" ] && source "${GHCUP_INSTALL_BASE_PREFIX:=$HOME}/.ghcup/env"
