export LC_ALL=es_ES.UTF-8
export LANG=es_ES.UTF-8
export TERM=xterm-256color
export VISUAL="vim"
export EDITOR="$VISUAL"

# tmux oh my zsh plugin
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOSTART_ONCE=true
ZSH_TMUX_FIXTERM=true
ZSH_TMUX_AUTOQUIT=true

# Load Antigen
source ~/.config/antigen/antigen.zsh

# Load Antigen configurations
antigen init ~/.config/antigen/antigenrc

# Alias
alias v=nvim

# On start
neofetch
